version: "3"
services:
  vulnerability:
    build: vulnerable-container/.
    ports:
      - "9000:443"
    volumes: 
      - ./vulnerable-container/html/:/var/www
  
  ccs-gateway:
    build: ccs-gateway/.
    ports:
      - "9002:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    links:
      - vulnerability:vulnerability
    volumes:
      - ./ccs-gateway/conf/nginx/:/etc/nginx

